[package]
name = "rust-the-book"
version = "0.1.0"
authors = ["runner"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "rust-the-book"
path = "projects/error_handling/main.rs"

[dependencies]
rand = "0.8.5"